### PR TITLE
Use JavaScriptCatalog view if Django version is >= 2.0

### PR DESCRIPTION
**Pull request by aminland**

### CODE REVIEW

**Comment by aminland** [comment]
@SalahAdDin as requested

**Comment by SalahAdDin** [comment]
@aminland , is this tested?

**Comment by aminland** [comment]
Not on this fork

**Comment by SalahAdDin** [comment]
You get a problem in the main repository, why? you removed packages from setup.

**Comment by aminland** [comment]
closing in favor of https://github.com/geex-arts/django-jet/pull/265

**Comment by SalahAdDin** [comment]
@aminland Seriously?

**Comment by aminland** [comment]
The other PR is more comprehensive for django 2

--
Amin Mirzaee

****************************************************************************
Confidentiality Warning: This message and any attachments are intended only
for the use of the intended recipient(s), are confidential, and may be
privileged. If you are not the intended recipient, you are hereby notified
that any review, retransmission, conversion to hard copy, copying,
circulation or other use of this message and any attachments is strictly
prohibited. If you are not the intended recipient, please notify the sender
immediately by return e-mail, and delete this message and any attachments
from your system. Thank-you!
****************************************************************************

**Pull request closed without merging**
